[package]
name = "pathrs-shader"
version = "0.1.0"
edition = "2021"
authors = ["Finn Vos <finn@fvos.de>"]
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
pathrs-shared = { path = "../pathrs-shared" }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", branch = "main" }
